name = "CxxWrapTestRegistry"
uuid = "e552e162-ce81-4602-898c-f3edd3480370"
repo = "git@github.com:barche/CxxWrapTestRegistry.git"
description = "CxxWrap-based experimental JLL packages"

[packages]
3eaa8342-bff7-56a5-9981-c04077f7cee7 = { name = "libcxxwrap_julia_jll", path = "L/libcxxwrap_julia_jll" }
629bc702-f1f5-5709-abd5-49b8460ea067 = { name = "Qt6Declarative_jll", path = "Q/Qt6Declarative_jll" }
c0090381-4147-56d7-9ebc-da0b1113ec56 = { name = "Qt6Base_jll", path = "Q/Qt6Base_jll" }
ce943373-25bb-56aa-8eca-768745ed7b5a = { name = "Qt6ShaderTools_jll", path = "Q/Qt6ShaderTools_jll" }
