name = "CxxWrapTestRegistry"
uuid = "e552e162-ce81-4602-898c-f3edd3480370"
repo = "git@github.com:barche/CxxWrapTestRegistry.git"
description = "CxxWrap-based experimental JLL packages"

[packages]
3eaa8342-bff7-56a5-9981-c04077f7cee7 = { name = "libcxxwrap_julia_jll", path = "L/libcxxwrap_julia_jll" }
6b5019fb-a83d-5b4e-a9f7-678a36c28df7 = { name = "jlqml_jll", path = "J/jlqml_jll" }
be234c1c-6cf4-5063-8676-3229d64ce17a = { name = "GRQt5_jll", path = "jll/G/GRQt5_jll" }
f74edf77-fc28-5533-a68a-cacf3c4a2f46 = { name = "GRCore_jll", path = "jll/G/GRCore_jll" }
