name = "CxxWrapTestRegistry"
uuid = "e552e162-ce81-4602-898c-f3edd3480370"
repo = "git@github.com:barche/CxxWrapTestRegistry.git"
description = "CxxWrap-based experimental JLL packages"

[packages]
3eaa8342-bff7-56a5-9981-c04077f7cee7 = { name = "libcxxwrap_julia_jll", path = "L/libcxxwrap_julia_jll" }
